version: "3"
services:
  database:
    image: postgres
    restart: always
    container_name: security_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: security
    ports:
        - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data