create table if not exists public.reviews
(
    id          bigint not null generated by default as identity
        constraint reviews_pk
            primary key,
    order_id bigint
        constraint reviews_orders_id_fk
            references public.orders,
    rating      integer,
    comment      varchar
);

alter table public.reviews
    owner to postgres;
